export const LOC_STORE_REC_SEARCHES = 'LOC_STORE_REC_SEARCHES';

export const GET_BREWERIES = 'GET_BREWERIES';
export const BREWERIES_ERROR = 'BREWERIES_ERROR';

export const GET_WEATHER = 'GET_WEATHER';
export const WEATHER_ERROR = 'WEATHER_ERROR';

export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const RESTAURANTS_ERROR = 'RESTAURANTS_ERROR';

export const GET_PLACES_HISTORY = 'GET_PLACES_HISTORY';
